name: Build Android APK

on:
  push:
    branches:
      - main
      - master
      - 'integra*'
      - 'Update*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Dependencias
        run: npm install --legacy-peer-deps

      - name: Build do Site (Ionic/Angular)
        run: npm run build

      - name: Corrigir Permissao do Gradle
        run: chmod +x android/gradlew

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Gerar APK (Gradle)
        run: cd android && ./gradlew assembleDebug

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk